In [2]:
import numpy as np


1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32

In [3]:
lst = [12.23, 13.32, 100, 36.32]
one_d = np.array(lst)
print(one_d)

[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [4]:
matrix = np.random.randint(2,10,size=(3,3))
print(matrix)

[[2 9 2]
 [5 6 4]
 [3 3 5]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [5]:
null_vector = np.zeros(10)
null_vector[5] = 11
print(null_vector)



[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [6]:
lst = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 ,27, 28, 29, 30, 31, 32,33, 34, 35, 36, 37]
rev = np.flip(lst)
print(rev)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [7]:
array = np.ones((5,5))
print("original array : ")
print(array)
print("1 on the border and 0 inside in the array")
array[1:-1,1:-1] = 0
print(array)


original array : 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [8]:
arr = np.zeros((5,5))
print("original array:")
print(arr)
arr[1:-1,1:-1] = 1
print("output")
print(arr)

original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
output
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [9]:
mat = np.zeros((8,8),dtype= int)
# assign the value 1 to every other element in every other row starting from index 1
mat[1::2,::2] = 1
# assign the value 1 to every other element in every other col starting from index 1
mat[::2,1::2] = 1
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [10]:
lst = [1,2,3,4,5,6,7,8]
print(type(lst))
print(np.asarray(lst))
tup = ([8,4,6],[1,2,3])
print(np.asarray(tup))
print(type(tup))


<class 'list'>
[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]
<class 'tuple'>


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [11]:
lst = [10,20,30]
lst = np.append(lst,[40,50,60,70,80,90])
print(lst)

[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [12]:
x = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
print("original array")
print(x)
print("Real part of array:")
print(x.real)
print("Imaginary part of the array:")
print(x.imag)

original array
[1.        +0.j         0.70710678+0.70710678j]
Real part of array:
[1.         0.70710678]
Imaginary part of the array:
[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [13]:
array = np.array([1,3,5,], dtype = np.float64)
print(f"Sixe of the array :", array.size)
print("Length of one array element in bytes:", array.itemsize)
print("Total bytes consumed by the elements of the array:",array.nbytes)


Sixe of the array : 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [14]:
arr1 = [0, 10, 20, 40, 60]
arr2 = [10, 30, 40]
print("comman values :")
# intersection means common value in both array
print(np.intersect1d(arr1,arr2))


comman values :
[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [15]:
Array1 =  [ 0,10, 20, 40, 60, 80]
Array2 =  [10, 30, 40, 50, 70, 90]
print("Set difference between two arrays:")
print(np.setdiff1d(Array1,Array2))

Set difference between two arrays:
[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [16]:
Array1 =  [ 0,10, 20, 40, 60, 80]
Array2 =  [10, 30, 40, 50, 70,]
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(Array1,Array2))

Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [17]:
a = np.array([1,2])
b = np.array([4,5])
print("a>b")
print(np.greater(a,b))
print("a>=b")
print(np.greater_equal(a,b))
print("a<=b")
print(np.less_equal(a,b))

a>b
[False False]
a>=b
[False False]
a<=b
[ True  True]


15. Write a Python program to save a NumPy array to a text file.


In [19]:
arr = np.array([1,3,4])
np.savetxt("1.txt",arr)
ans = np.loadtxt('1.txt')
print("valur in file",ans)

valur in file [1. 3. 4.]


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [20]:
array = np.array([[10,20,30],[20,40,50]])
print("New flattened array:")
print(array.flatten())


New flattened array:
[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [25]:
array = np.array([[2,4,6],[6,8,10]])
print(array)
print("Data type of the array x is:" ,array.dtype)

array = np.array([[2,4,6],[6,8,10]],dtype = np.float64)
print(array)
print(array.dtype)


[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
float64


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [41]:
arr = np.zeros((1,3,3))
arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]


In [54]:
arr = np.tri(4,3,-1)
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]])
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [65]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
c = np.concatenate((a,b),1)
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
